local log = require("shared.log")

local DeviceManager = {
    initialized = false,
    devices = {},
}

-- Private: Bind a specific device to its driver
local function bind_device(device, driver_map)
    local package_name = driver_map[device.type]

    if not package_name then
        device.status = "error"
        device.error = "No driver registered for type: " .. device.type
        return
    end

    -- The "Lattice Rule": require path matches package name
    local ok, driver_def = pcall(require, package_name)
    if not ok then
        device.status = "error"
        device.error = "Failed to load driver package: " .. package_name
        log.error(device.error)
        return
    end

    local ok2, instance = pcall(driver_def.init, device.peripheral)
    if not ok2 then
        device.status = "error"
        device.error = "Driver init failed: " .. tostring(instance)
        log.error(device.error)
        return
    end

    device.driver = instance
    device.status = "ok"
    log.trace("Device '" .. device.name .. "' bound to '" .. package_name .. "'")
end

function DeviceManager.init()
    if DeviceManager.initialized then return end
    log.trace("Initializing device manager")

    -- Load the pre-compiled driver map generated by Mesh
    local map_path = "/os/drivers.lua"
    if not fs.exists(map_path) then
        log.error("Driver map missing at " .. map_path)
        return
    end
    local driver_map = loadfile(map_path)()

    -- Scan and bind
    DeviceManager.devices = {}
    for _, name in ipairs(peripheral.getNames()) do
        local ok, wrapped = pcall(peripheral.wrap, name)
        if ok then
            local device = {
                name = name,
                type = peripheral.getType(name),
                peripheral = wrapped,
                status = "unbound"
            }
            bind_device(device, driver_map)
            table.insert(DeviceManager.devices, device)
        end
    end

    DeviceManager.initialized = true
    log.trace("Device manager initialized")
end

function DeviceManager.get_devices()
    return DeviceManager.devices
end

-- Event Handlers for hot-swap
function DeviceManager.handle_attach(name)
    local map_path = "/os/drivers.lua"
    local driver_map = loadfile(map_path)()

    local ok, wrapped = pcall(peripheral.wrap, name)
    if ok then
        local device = {
            name = name,
            type = peripheral.getType(name),
            peripheral = wrapped,
            status = "unbound"
        }
        bind_device(device, driver_map)
        table.insert(DeviceManager.devices, device)
        return device
    end
end

return DeviceManager
